export const SUCCESS_SEARCH = 'SUCCESS/LIST/SEARCH';
export const FAILURE_SEARCH = 'FAILURE/LIST/SEARCH';

export const SEARCH_STARTED = 'SEARCH/STARTED';
export const SEARCH_SUCCESS = 'SEARCH/SUCCESS';
export const SEARCH_FAILURE = 'SEARCH/FAILURE';
