export const ADD_COMMENT = 'COMMENT/ADD';
export const CHECK_COMMENT = 'COMMENT/CHECKED';
export const DELETE_COMMENT = 'COMMENT/DELETE';
export const INIT_COMMENT = 'COMMENT/INIT';
export const INIT_ALL_COMMENT = 'COMMENT/INIT/ALL';
export const NOTCHECKED_COMMENT = 'COMMENT/INIT/NOTCHECKED';
export const SET_COMMENT_FILTER = 'COMMENT/SET/FILTER';
