export const ADD_COMMENT = "COMMENT/ADD";
export const ADD_SUB_COMMENT = "COMMENT/ADD/SUB";
export const CHECK_COMMENT = "COMMENT/CHECKED";
export const DELETE_COMMENT = "COMMENT/DELETE";
export const CANCEL_COMMENT = "COMMENT/CANCEL";
export const DELETE_SUB_COMMENT = "COMMENT/DELETE/SUB";
export const CHANCEL_SUB_COMMENT = "COMMENT/CHANCEL/SUB";
export const INIT_COMMENT = "COMMENT/INIT";
export const INIT_ALL_COMMENT = "COMMENT/INIT/ALL";
export const NOTCHECKED_AND_REPORT_COMMENT =
  "COMMENT/INIT/NOTCHECKED/AND/REPORTED";
export const SET_COMMENT_FILTER = "COMMENT/SET/FILTER";
export const SET_SHOW_REPLY = "COMMENT/SET/SHOW/REPLY";
export const SET_ADMIN_SHOW_REPLY = "COMMENT/SET/SHOW/ADMIN/REPLY";
export const SET_THUMBSUP = "COMMENT/SET/HTUMBSUP";
export const SET_THUMBSDOWN = "COMMENT/SET/HTUMBSDOWN";
export const SET_REPORT = "COMMENT/SET/REPORT";
