export const REGIST_START = 'REGIST/STARTED';
export const REGIST_SUCCESS = 'REGIST/SUCCESS';
export const REGIST_FAILURE = 'REGIST/FAILURE';

export const REGIST_ALERT_SUCCESS = 'REGISTALERT/SUCCESS';
export const REGIST_ALERT_FAILE = 'REGIST/ALERT/FAILE';
