export const UPDATE_STARTED = 'UPDATE/STARTED';
export const UPDATE_SUCCESS = 'UPDATE/SUCCESS';
export const UPDATE_FAILURE = 'UPDATE/FAILURE';

export const UPDATE_ALERT_INIT = 'UPDATE/ALERT/INIT';
export const UPDATE_ALERT_FAIL = 'UPDATE/ALERT/FAIL';
export const UPDATE_ALERT_SUCCESS = 'UPDATE/ALERT/SUCCESS';

