export const CONFIG_INIT = "CONFIG/INIT";
export const CONFIG_SET_KEEPONFILE = "CONFIG/SET/KEEPONFILE";
export const CONFIG_SET_SEARCHPAGE = "CONFIG/SET/SEARCHPAGE";
export const CONFIG_SET_ARTICLEDETAILS = "CONFIG/SET/ARTICLEDETAILS";
export const CONFIG_SET_COMMENTS = "CONFIG/SET/COMMENTS";
export const CONFIG_SET_BASIC = "CONFIG/SET/BASIC";
