export const LOGIN_IN = 'LOGIN/LOGININ';
export const LOGIN_OUT = 'LOGIN/LOGINOUT';

export const LOGIN_STARTED = 'LOGIN/STARTED';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/FAILURE';

export const LOGIN_ALERT_FAILE = 'LOGIN/ALERT/FAILE';
export const LOGIN_ALERT_SUCCESS = 'LOGIN/ALERT/SUCCESS';

