export const ADD_MESSAGE = "MESSAGE/ADD";
export const NOTCHECKED_MESSAGE = "MESSAGE/NOTCHECKED";
export const INIT_ALL_MESSAGE = "MESSAGE/INIT/ALL";
export const SET_MESSAGE_FILTER = "MESSAGE/SET/FILTER";
export const CHECK_MESSAGE = "MESSAGE/CHECKED";
export const DELETE_MESSAGE = "MESSAGE/DELETE";
