export const ADD_ARTICLE = 'ARTICLE/ADD';
export const EDIT_ARTICLE = 'ARTICLE/EDIT';

export const POST_STARTED = 'POST/STARTED';
export const POST_SUCCESS = 'POST/SUCCESS';
export const POST_FAILURE = 'POST/FAILURE';

export const EDIT_INIT_START = 'EDIT/INITSTART';
export const EDIT_STARTED = 'EDIT/STARTED';
export const EDIT_SUCCESS = 'EDIT/SUCCESS';
export const EDIT_FAILURE = 'EDIT/FAILURE';

export const UPDATE_STARTED = 'UPDATE/STARTED';
export const UPDATE_SUCCESS = 'UPDATE/SUCCESS';
export const UPDATE_FAILURE = 'UPDATE/FAILURE';

